### PR TITLE
Add flake.nix

### PR DESCRIPTION
**Pull request by MagicRB**
Adds flake.nix, allows for development on NixOS

### CODE REVIEW

**Comment by MagicRB** [comment]
I'm still testing this, please hold off on merging

**Comment by futu2** [comment]
I don't understand why it costs that lots of code.
How did the pkgs.haskellPackages.h-raylib works? It seems work well before ( broken in unstable now).
I am not very familiar with nix, but why system default drv works well, is anybody make a patch to it?
See https://github.com/NixOS/nixpkgs/issues/197407

**Comment by MagicRB** [comment]
the problem is that `h-raylib` brings its own raylib and glfw. Which works well on other distros but is very un-NixOS-sy imo. Removing that simplifies packaging a lot.

**Comment by Anut-py** [comment]
I will have to update the git revision for raylib in `flake.nix` every time I pull the raylib source right?

**Comment by MagicRB** [comment]
there is no easy way to include a submodule. Nix doesn't do submodules.

**Comment by futu2** [comment]
After recheck code in nixpkgs, i.e. pkgs.haskellPackages.h-raylib, I found it fetch tar.gz directly from Hackage, and that works well with simplest callCabal2nix build scripts. The difference between tar.gz source code and this git repo, is in the raylib sub-folder, the hackage one contains a CmakeFiles folder, and that makes nix build works! see my repo directly using code downloaded form hackage https://github.com/futu2/h-raylib-4.6.0.7

**Comment by futu2** [comment]
```
diff h-raylib-4.6.0.7/raylib/ h-raylib/raylib/
```
```
Only in h-raylib/raylib/: BINDINGS.md
Only in h-raylib/raylib/: CHANGELOG
Only in h-raylib/raylib/: cmake
Only in h-raylib-4.6.0.7/raylib/: CMakeFiles
Only in h-raylib/raylib/: CMakeLists.txt
Only in h-raylib/raylib/: CMakeOptions.txt
Only in h-raylib/raylib/: CONTRIBUTING.md
Only in h-raylib/raylib/: CONVENTIONS.md
Common subdirectories: h-raylib-4.6.0.7/raylib/examples and h-raylib/raylib/examples
Only in h-raylib/raylib/: FAQ.md
Only in h-raylib/raylib/: .git
Only in h-raylib/raylib/: .github
Only in h-raylib/raylib/: .gitignore
Only in h-raylib/raylib/: HISTORY.md
Only in h-raylib/raylib/: LICENSE
Only in h-raylib/raylib/: logo
Common subdirectories: h-raylib-4.6.0.7/raylib/parser and h-raylib/raylib/parser
Common subdirectories: h-raylib-4.6.0.7/raylib/projects and h-raylib/raylib/projects
Only in h-raylib/raylib/: raylib.pc.in
Only in h-raylib/raylib/: README.md
Only in h-raylib/raylib/: ROADMAP.md
Common subdirectories: h-raylib-4.6.0.7/raylib/src and h-raylib/raylib/src
```

**Comment by futu2** [comment]
> there is no easy way to include a submodule. Nix doesn't do submodules.

Can nix flake fetch a raylib repo right in the ./. folder?
My simple callCabal2nix flake scripts run `nix build` successfully if delete git info by running `mv .git .git.bk`

**Comment by MagicRB** [comment]
yeah deleting .`git` is a horrible hack, nix just does not work with submodules.

**Pull request merged**
